global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Bdo.DatabaseLibrary1;
global using Jem.CommonLibrary22;
global using Jem.OcrLibrary22;
global using Microsoft.EntityFrameworkCore;